### ISSUE TITLE
ineffective use of popcount64

### ISSUE THREAD

**Issue by mikhaelkh** [kimwalisch/libpopcnt#9]
https://github.com/kimwalisch/libpopcnt/blob/328cc54e6cd6a9c3750150bcf63525ece4ab153d/libpopcnt.h#L658
popcount64 (uint64_t)
ptr[i] - uint8_t
I suppose this code'll be very slow on old x86 cpu's without POPCNT, when the whole array is processed in this line.

**Comment by kimwalisch** [comment]
>I suppose this code'll be very slow on old x86 cpu's without POPCNT, when the whole array is processed in this line.

Yes, you are absolutely right, it will run slow on CPUs without POPCNT. In the first few versions I also had specialized algorithms for old CPUs but because of code bloat the compiler was not inline-ing the ```popcnt()``` function. Hence I reduced the code bloat by removing the specialized algorithms for old CPUs.

Is it important to you that ```libpopcnt.h``` runs fast on old CPUs? If so I may put the specialized algorithms for old CPUs back in. But realistically, all x86 CPUs produced after 2010 have the POPCNT instruction. I guess the number of people still using CPUs from before 2010 is less than 1%...

**Comment by mikhaelkh** [comment]
No, it's not that important to me, but ~8x speed improvement (assuming that compiler haven't optimized popcount64 knowing that only 1 byte is nonzero) is quite obvious and simple - as popcnt64 falls back to popcount64 on cpu's with no POPCNT.
```c++
    cnt += popcnt64_unrolled((const uint64_t*) ptr, size / 8);
    ptr += size - size % 8;
    size = size % 8;

    for (i = 0; i < size; i++)
      cnt += popcnt64(ptr[i]);
```

**Comment by tlk00** [comment]
Sorry for barging into discussion, but 8x unrolling in my experience  does not give 8x performance boost. Yes, you can reduce the loop overhead (something optimized compiler will be able to do automatically in many cases) but POPCNT hw is expensive and not super-scalar (one exception pops per core for HW POPCNT on Intel). So speculative execution gains will not be applicable.

(I would be glad to be corrected.)

**Comment by mikhaelkh** [comment]
@tlk00 instead of `size` popcount64 calls there'll be `size/8+size%8` calls.

**Comment by tlk00** [comment]
popcount64() is a function with a very high chance to be inlined. There will be no call per se.

**Comment by kimwalisch** [comment]
> but ~8x speed improvement (assuming that compiler haven't optimized popcount64 knowing that only 1 byte is nonzero) is quite obvious and simple - as popcnt64 falls back to popcount64 on cpu's with no POPCNT.

Good point, I will improve ```libpopcnt.h``` for old CPUs using your suggestion.

However, the code change is a little more tricky than you might expect! Before calling ```popcnt64_unrolled()``` you have to ensure that the pointer is aligned to an 8 byte boundary. This is required because the compiler may vectorize ```popcnt64_unrolled()``` and then you get a segmentation fault if you call the ```popcnt()``` function with a data pointer that is not aligned to an 8 byte boundary.

**Comment by mikhaelkh** [comment]
> Before calling popcnt64_unrolled() you have to ensure that the pointer is aligned to an 8 byte boundary. This is required because the compiler may vectorize popcnt64_unrolled() and then you get a segmentation fault if you call the popcnt() function with a data pointer that is not aligned to an 8 byte boundary.

https://github.com/kimwalisch/libpopcnt/blob/328cc54e6cd6a9c3750150bcf63525ece4ab153d/libpopcnt.h#L645
Then you need to align here too. I'm pretty sure that compiler won't auto-vectorize unaligned data by himself, but of course it would be better to align first.

**Comment by kimwalisch** [comment]
> Then you need to align here too. 

Theoretically you are right :-) But practically aligning is not needed here because the compiler cannot vectorize this code because there are no x86 CPUs with vector POPCNT instructions.

**Comment by kimwalisch** [comment]
I have implemented the improvement for old x86 CPUs without POPCNT, see https://github.com/kimwalisch/libpopcnt/commit/3bd3768f1fa1526e520c4873b4ab3bf48343c65b. According to my benchmarks the new code runs up to 6 times faster on old x86 CPUs without POPCNT! On new x86 CPUs with POPCNT the new code runs just as fast as the old code.

**Comment by mikhaelkh** [comment]
@kimwalisch also can you run benchmark on old x86 CPUs without POPCNT, but instead of your `popcount64` use `__builtin_popcountll` and `march=native`. Do you know which algo GCC/Clang use for `__builtin_popcount(ll)`?

**Comment by kimwalisch** [comment]
Below is the code GCC uses for ```__builtin_popcount()``` (https://github.com/gcc-mirror/gcc/blob/da8dff89fa9398f04b107e388cb706517ced9505/libgcc/libgcc2.c#L866) on old x86 CPUs without POPCNT and even on new CPUs when compiling without ```-mpopcnt```. For ```__builtin_popcountll()``` GCC simply calls ```__builtin_popcount()``` twice.

```C
int
__popcountDI2 (UDWtype x)
{
  /* Force table lookup on targets like AVR and RL78 which only
     pretend they have LIBGCC2_UNITS_PER_WORD 4, but actually
     have 1, and other small word targets.  */
#if __SIZEOF_INT__ > 2 && defined (POPCOUNTCST) && __CHAR_BIT__ == 8
  const DWunion uu = {.ll = x};
  UWtype x1 = uu.s.low, x2 = uu.s.high;
  x1 = x1 - ((x1 >> 1) & POPCOUNTCST (0x55));
  x2 = x2 - ((x2 >> 1) & POPCOUNTCST (0x55));
  x1 = (x1 & POPCOUNTCST (0x33)) + ((x1 >> 2) & POPCOUNTCST (0x33));
  x2 = (x2 & POPCOUNTCST (0x33)) + ((x2 >> 2) & POPCOUNTCST (0x33));
  x1 = (x1 + (x1 >> 4)) & POPCOUNTCST (0x0F);
  x2 = (x2 + (x2 >> 4)) & POPCOUNTCST (0x0F);
  x1 += x2;
  return (x1 * POPCOUNTCST (0x01)) >> (W_TYPE_SIZE - __CHAR_BIT__);
#else
  int i, ret = 0;

  for (i = 0; i < 2*W_TYPE_SIZE; i += 8)
    ret += __popcount_tab[(x >> i) & 0xff];

  return ret;
#endif
}
```

This counts the number of 1 bits using only integer instructions (shift, logical, multiplication). It is similar to ```libpopcnt.h``` but it uses ```int``` type instead of ```int64_t```. So on old x86 CPUs when compiling in 64-bit mode ```libpopcnt.h``` should be roughly twice as fast.

Also this code is part of libgcc, hence the compiler won't inline ```__builtin_popcount*()``` on old x86 CPUs which also causes a slowdown compared to ```libpopcnt.h```.

I have benchmarked my new code vs. ```__builtin_popcountll()``` on old x86 CPUs without POPCNT using GCC 7.2 and found that ```libpopcnt.h``` runs about twice as fast as GCC ```__builtin_popcountll()```.

**Comment by mikhaelkh** [comment]
Thanks for such detailed answer!
> and even on new CPUs when compiling without `-mpopcnt`

You can override this by using `#pragma GCC target("popcnt")` or `__attribute__((__target__ ("popcnt")))`
> libpopcnt.h runs about twice as fast as GCC __builtin_popcountll()

Good enough. Closing issue.
